### PR TITLE
avoid crash in MediaPreviewActivity.onPageUnselected

### LINKED ISSUE #3542: IllegalArgumentException in DcMediaGalleryElement.moveToPosition
```
Exception java.lang.IllegalArgumentException:
  at com.b44t.messenger.DcMediaGalleryElement.moveToPosition (DcMediaGalleryElement.java:37)
  at org.thoughtcrime.securesms.MediaPreviewActivity$DcMediaPagerAdapter.getMediaItemFor (MediaPreviewActivity.java:629)
  at org.thoughtcrime.securesms.MediaPreviewActivity$ViewPagerListener.onPageUnselected (MediaPreviewActivity.java:476)
  at org.thoughtcrime.securesms.components.viewpager.ExtendedOnPageChangedListener.onPageSelected (ExtendedOnPageChangedListener.java:17)
  at org.thoughtcrime.securesms.MediaPreviewActivity$ViewPagerListener.onPageSelected (MediaPreviewActivity.java:458)
  at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected (ViewPager.java:1947)
  at androidx.viewpager.widget.ViewPager.setCurrentItemInternal (ViewPager.java:665)
  at androidx.viewpager.widget.ViewPager.setCurrentItemInternal (ViewPager.java:631)
  at androidx.viewpager.widget.ViewPager.setCurrentItem (ViewPager.java:612)
  at org.thoughtcrime.securesms.MediaPreviewActivity.onLoadFinished (MediaPreviewActivity.java:445)
  at org.thoughtcrime.securesms.MediaPreviewActivity.onLoadFinished (MediaPreviewActivity.java:75)
  at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged (LoaderManagerImpl.java:250)
  at androidx.lifecycle.LiveData.considerNotify (LiveData.java:133)
  at androidx.lifecycle.LiveData.dispatchingValue (LiveData.java:151)
  at androidx.lifecycle.LiveData.setValue (LiveData.java:309)
  at androidx.lifecycle.MutableLiveData.setValue (MutableLiveData.java:50)
  at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue (LoaderManagerImpl.java:189)
  at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete (LoaderManagerImpl.java:174)
  at androidx.loader.content.Loader.deliverResult (Loader.java:132)
  at org.thoughtcrime.securesms.util.AsyncLoader.deliverResult (AsyncLoader.java:48)
  at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete (AsyncTaskLoader.java:258)
  at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute (AsyncTaskLoader.java:83)
  at androidx.loader.content.ModernAsyncTask.finish (ModernAsyncTask.java:490)
  at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage (ModernAsyncTask.java:507)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8031)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:620)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1011)
```

### PR DESCRIPTION
**Pull request by adbenitez**
close #3542

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java [hunk 1]
```diff
@@ -472,9 +472,12 @@ public void onPageUnselected(int position) {
...
 
       if (adapter != null) {
-        MediaItem item = adapter.getMediaItemFor(position);
-        if (item.recipient != null) item.recipient.removeListener(MediaPreviewActivity.this);
-
+        try {
+          MediaItem item = adapter.getMediaItemFor(position);
+          if (item.recipient != null) item.recipient.removeListener(MediaPreviewActivity.this);
+        } catch (IllegalArgumentException e) {
+          e.printStackTrace();
```
Comment (Hocuri) [inline src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java:479]: Can use `Log.w`

**Review by Hocuri — APPROVED** [review]
