### PR TITLE
avoid SecurityException in NotificationsPreferenceFragment

### LINKED ISSUE #3717: SecurityException in NotificationsPreferenceFragment
in `org.thoughtcrime.securesms.preferences.NotificationsPreferenceFragment$RingtoneSummaryListener.onPreferenceChange`

```
Exception java.lang.SecurityException:
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3089)
  at android.os.Parcel.createException (Parcel.java:3073)
  at android.os.Parcel.readException (Parcel.java:3056)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:190)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:142)
  at android.content.ContentProviderProxy.call (ContentProviderNative.java:764)
  at android.provider.Settings$NameValueCache.putStringForUser (Settings.java:3180)
  at android.provider.Settings$System.putStringForUser (Settings.java:4011)
  at android.provider.Settings$System.putStringForUser (Settings.java:3991)
  at android.provider.Settings$System.putStringForUser (Settings.java:3985)
  at android.media.RingtoneManager.setActualDefaultRingtoneUri (RingtoneManager.java:1393)
  at android.media.RingtoneManager.getActualDefaultRingtoneUri (RingtoneManager.java:1343)
  at android.media.Ringtone.getTitle (Ringtone.java:418)
  at android.media.Ringtone.getTitle (Ringtone.java:401)
  at org.thoughtcrime.securesms.preferences.NotificationsPreferenceFragment$RingtoneSummaryListener.onPreferenceChange (NotificationsPreferenceFragment.java:162)
  at org.thoughtcrime.securesms.preferences.NotificationsPreferenceFragment.initializeRingtoneSummary (NotificationsPreferenceFragment.java:213)
  at org.thoughtcrime.securesms.preferences.NotificationsPreferenceFragment.onCreate (NotificationsPreferenceFragment.java:74)
  at androidx.fragment.app.Fragment.performCreate (Fragment.java:3090)
  at androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:475)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:257)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1899)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1817)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1760)
  at androidx.fragment.app.FragmentManager$5.run (FragmentManager.java:547)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:243)
  at android.os.Looper.loop (Looper.java:338)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1064)
```

### PR DESCRIPTION
**Pull request by adbenitez**
close #3717

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java [hunk 1]
```diff
@@ -159,7 +161,17 @@ public boolean onPreferenceChange(@NonNull Preference preference, Object newValu
...
         if (tone != null) {
-          preference.setSummary(tone.getTitle(getActivity()));
+          String summary;
+          try {
+            summary = tone.getTitle(getActivity());
+          } catch (SecurityException e) {
+            // this could happen in some phones when user selects ringtone from
+            // external storage and later removes the read from external storage permission
+            // and later this method is called from initializeRingtoneSummary()
+            summary = "???";
```
Comment (r10s) [inline src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java:171]: maybe mention the situation shown in the comment more precisely - this also has the advantage that it is easier grep'able if it happens gain

```suggestion
            summary = "<no access>";
```

**Review by r10s — APPROVED** [review]
nice, thanks for talking care.

feel free  to apply or to ignore my suggestion :)
