### PR TITLE
avoid NullPointerException in DcMsg.msgSetToIds()

### LINKED ISSUE #1967: Possible null-pointer-exception.
- Android version:
- Device:
- Delta Chat version:
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

deltachat-android/src/com/b44t/messenger/DcMsg.java 

 public static int[] msgSetToIds(final Set<DcMsg> dcMsgs) {
        int   cnt = dcMsgs==null? 0 : dcMsgs.size(); // If dcMsgs is null, cnt is set to zero. See below.
        int[] ids = new int[cnt];
        int   i = 0;
        for (DcMsg dcMsg : dcMsgs) { // dcMsgs == null?
            ids[i++] = dcMsg.getId();
        }
        return ids;
    }

### PR DESCRIPTION
**Pull request by adbenitez**
close #1967

### CODE REVIEW

File: src/com/b44t/messenger/DcMsg.java [hunk 1]
```diff
@@ -145,8 +145,9 @@ public File getFileAsFile() {
 
     // aliases and higher-level tools
     public static int[] msgSetToIds(final Set<DcMsg> dcMsgs) {
-        int   cnt = dcMsgs==null? 0 : dcMsgs.size();
-        int[] ids = new int[cnt];
+        if(dcMsgs==null)
+            return new int[0];
```
Comment (r10s) [inline src/com/b44t/messenger/DcMsg.java:149]: in general, it is a good idea to always surround code blocks by curly brackets:

```suggestion
        if (dcMsgs == null) {
            return new int[0];
        }
```

**Review by r10s — APPROVED** [review]
lgtm, apart from the minor code style comments.

thanks for taking care!
