### PR TITLE
Fix dialogs not showing when pasted QR codes are not valid

### LINKED ISSUE #4160: adding relay: no error dialog on pasting invalid link
- Android version: 11
- Device: OnePlus A3003
- Delta Chat version: 2.35-foss
- Expected behavior: visible error dialog like when scanning invalid QR codes elsewhere in the app
- Actual behavior: no user feedback, just goes back to relay overview and looks like it is not working
- Steps to reproduce the problem: try to add a relay copying some invalid link (neither `dcaccount` nor `dclogin`)

I got there because I copied the link to a QR code image of the chatmail relay and not the actual link of the image and at first I was a bit annoyed because I thought there would be a bug in the app, but fortunately it is "just" a missing error dialog.

### PR DESCRIPTION
**Pull request by wchen342**
The dialogs are built correctly, but are not actually shown.

closes #4160

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/NewConversationActivity.java [hunk 1]
```diff
@@ -138,10 +138,10 @@ protected void onActivityResult(int requestCode, int resultCode, Intent data) {
     super.onActivityResult(requestCode, resultCode, data);
     if (resultCode != RESULT_OK) return;
 
+    QrCodeHandler qrCodeHandler = new QrCodeHandler(this);
     switch (requestCode) {
       case IntentIntegrator.REQUEST_CODE:
         IntentResult scanResult = IntentIntegrator.parseActivityResult(resultCode, data);
-        QrCodeHandler qrCodeHandler = new QrCodeHandler(this);
         qrCodeHandler.handleOnlySecureJoinQr(scanResult.getContents(), SecurejoinSource.Scan, SecurejoinUiPath.NewContact);
```
Comment (adbenitez) [inline src/main/java/org/thoughtcrime/securesms/NewConversationActivity.java]: this change seems unnecessary or leftovers of experimenting/testing

Comment (wchen342) [reply src/main/java/org/thoughtcrime/securesms/NewConversationActivity.java]: I was thinking the initialization can be moved out of switch. I will keep it then.
