### PR TITLE
avoid NPE in UriGlideRenderer

### LINKED ISSUE #3721: NPE in org.thoughtcrime.securesms.scribbles.UriGlideRenderer.writeToParcel
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
  at org.thoughtcrime.securesms.scribbles.UriGlideRenderer.writeToParcel (UriGlideRenderer.java:306)
  at android.os.Parcel.writeParcelable (Parcel.java:1953)
  at org.thoughtcrime.securesms.imageeditor.model.EditorElement.writeToParcel (EditorElement.java:350)
  at android.os.Parcel.writeTypedObject (Parcel.java:1786)
  at android.os.Parcel.writeTypedList (Parcel.java:1665)
  at android.os.Parcel.writeTypedList (Parcel.java:1622)
  at org.thoughtcrime.securesms.imageeditor.model.EditorElement.writeToParcel (EditorElement.java:352)
  at android.os.Parcel.writeTypedObject (Parcel.java:1786)
  at android.os.Parcel.writeTypedList (Parcel.java:1665)
  at android.os.Parcel.writeTypedList (Parcel.java:1622)
  at org.thoughtcrime.securesms.imageeditor.model.EditorElement.writeToParcel (EditorElement.java:352)
  at android.os.Parcel.writeTypedObject (Parcel.java:1786)
  at android.os.Parcel.writeTypedList (Parcel.java:1665)
  at android.os.Parcel.writeTypedList (Parcel.java:1622)
  at org.thoughtcrime.securesms.imageeditor.model.EditorElement.writeToParcel (EditorElement.java:352)
  at android.os.Parcel.writeTypedObject (Parcel.java:1786)
  at android.os.Parcel.writeTypedList (Parcel.java:1665)
  at android.os.Parcel.writeTypedList (Parcel.java:1622)
  at org.thoughtcrime.securesms.imageeditor.model.EditorElement.writeToParcel (EditorElement.java:352)
  at android.os.Parcel.writeParcelable (Parcel.java:1953)
  at org.thoughtcrime.securesms.imageeditor.model.ElementStack.getBytes (ElementStack.java:63)
  at org.thoughtcrime.securesms.imageeditor.model.UndoRedoStacks.clear (UndoRedoStacks.java:73)
  at org.thoughtcrime.securesms.imageeditor.model.EditorModel.addElementWithoutPushUndo (EditorModel.java:690)
  at org.thoughtcrime.securesms.imageeditor.model.EditorModel.addElement (EditorModel.java:680)
  at org.thoughtcrime.securesms.scribbles.ImageEditorFragment.onViewCreated (ImageEditorFragment.java:144)
  at androidx.fragment.app.Fragment.performViewCreated (Fragment.java:3128)
  at androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:552)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:261)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1899)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1817)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1760)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2985)
  at androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java:2895)
  at androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java:263)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:351)
  at androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:251)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1457)
  at android.app.Activity.performStart (Activity.java:8259)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3776)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2311)
  at android.os.Handler.dispatchMessage (Handler.java:111)
  at android.os.Looper.loopOnce (Looper.java:238)
  at android.os.Looper.loop (Looper.java:357)
  at android.app.ActivityThread.main (ActivityThread.java:8090)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1026)
```

### PR DESCRIPTION
**Pull request by adbenitez**
close #3721 

#skip-changelog

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/scribbles/UriGlideRenderer.java [hunk 1]
```diff
@@ -303,7 +303,7 @@ public int describeContents() {
 
   @Override
   public void writeToParcel(Parcel dest, int flags) {
-    dest.writeString(imageUri.toString());
+    dest.writeString(imageUri!=null? imageUri.toString() : "");
```
Comment (adbenitez) [inline src/main/java/org/thoughtcrime/securesms/scribbles/UriGlideRenderer.java:306]: tbh, not sure what that Parcel thing is and if it is better to write to parcel in this case or just "do nothing" in this case

Comment (r10s) [reply src/main/java/org/thoughtcrime/securesms/scribbles/UriGlideRenderer.java:306]: "Parcel" is used for serialising and unserializing things, usually for IPC or so, https://developer.android.com/reference/android/os/Parcel

not totally sure for what it is needed here, might be some relict of Signal code.

in any case, this fixes as crash :)

**Review by r10s — APPROVED** [review]
thanks for fixing!
