### PR TITLE
Fix the image-is-cropped-too-much-bug

### LINKED ISSUE #1797: (Preview) Images of photos and videos distorted after toggling portrait->landscape->portrait view
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-02-05).

- Delta Chat Version:
1.15.0-beta.

- Expected behavior:
Images of photos and videos are shown with correct ratio after toggling from portrait to landscape view and back again.

- Actual behavior:
Images of photos and videos are distorted after toggling from portrait to landscape view and back again.

- Steps to reproduce the problem:
-- Enlarge/Play a photo/video while in portrait view.
-- Rotate the view from portrait to landscape.
-- Select "Show in chat" from the three-dot menu (on right top).
-- Rotate back to portrait view. (Result: The image of the selected photo/video is distorted.)

- Screenshots:
-- Expected:
grafik
-- Actual:
grafik

- Logs:
N/A.

### PR DESCRIPTION
**Pull request by Hocuri**
fix  #1797

Apparently, we ran into a bug similar to the one described in
https://github.com/bumptech/glide/issues/613#issuecomment-144762087 as
we cropped twice (in addition to the cropping I removed, we also set
`android:scaleType="centerCrop"` in `thumbnail_view.xml`)

### CODE REVIEW

File: src/org/thoughtcrime/securesms/components/ThumbnailView.java [hunk 1]
```diff
@@ -290,18 +290,6 @@ protected void onPostExecute(Boolean success) {
     return result;
   }
 
-  public ListenableFuture<Boolean> setImageResource(@NonNull GlideRequests glideRequests, @NonNull Uri uri) {
-    SettableFuture<Boolean> future = new SettableFuture<>();
-
-    glideRequests.load(new DecryptableUri(uri))
-                 .diskCacheStrategy(DiskCacheStrategy.NONE)
-                 .transforms(new CenterCrop(), new RoundedCorners(radius))
```
Comment (Hocuri) [inline src/org/thoughtcrime/securesms/components/ThumbnailView.java:298]: Removing this unused function has nothing to do with my PR, but it felt better to have removed all `CenterCrop` from this file :)

**Review by r10s — APPROVED** [review]
lgtm, code-wise, maybe also remove the now unused `applySizing()`.

did/can you test that the changes introduced by https://github.com/deltachat/deltachat-android/pull/1688 (wide and tall images etc.) are not affected by this fix? that seems to be a very sensible area :)

**Comment by Hocuri** [comment]
> did/can you test that the changes introduced by #1688 (wide and tall images etc.) are not affected by this fix? that seems to be a very sensible area :)

Yes, it's still working fine.

**Review by r10s — APPROVED** [review]
lgtm, thanks for taking care!

also here, i think, it is good to merge that in soon :)
