### PR TITLE
fix sound notifications, allow to set to "silent"

### LINKED ISSUE #1753: General (system) notification sound played when selected "None"
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-12-04).

- Delta Chat Version:
1.14.5, latest master build.

- Expected behavior:
When no notification sound ("None") is set, Delta Chat does not play a sound after a new message is received.

- Actual behavior:
When no notification sound ("None") is set, Delta Chat plays the general notification sound configured in Android.

- Steps to reproduce the problem:
-- In "Settings" -> "Notifications" -> "Sound" choose "None".
-- Wait for an incoming message. (Result: The general notification sound is played.)

- Screenshots:
N/A.

- Logs:
N/A.

- Credits:
Reported by user "Gh0stz" from Delta Chat group "Testing Delta Chat".

### PR DESCRIPTION
**Pull request by adbenitez**
close #1753

### CODE REVIEW

File: src/org/thoughtcrime/securesms/notifications/NotificationCenter.java [hunk 1]
```diff
@@ -173,7 +173,7 @@ private PendingIntent getMarkAsReadIntent(int chatId, boolean markNoticed) {
 
     // channelIds: CH_MSG_* are used here, the other ones from outside (defined here to have some overview)
     public static final String CH_MSG_PREFIX = "ch_msg";
-    public static final String CH_MSG_VERSION = "4";
+    public static final String CH_MSG_VERSION = "5";
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/notifications/NotificationCenter.java:176]: this is needed to avoid reusing old deleted channels with wrong configuration (default sound in silent mode)

File: src/org/thoughtcrime/securesms/notifications/NotificationCenter.java [hunk 2]
```diff
@@ -291,6 +291,8 @@ private String getNotificationChannel(NotificationManagerCompat notificationMana
                                 new AudioAttributes.Builder().setContentType(AudioAttributes.CONTENT_TYPE_UNKNOWN)
                                         .setUsage(AudioAttributes.USAGE_NOTIFICATION_COMMUNICATION_INSTANT)
                                         .build());
+                    } else {
+                        channel.setSound(null, null);
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/notifications/NotificationCenter.java:295]: without doing this, default sound is used instead of none/silent

File: src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java [hunk 3]
```diff
@@ -49,6 +49,7 @@ public void onCreate(Bundle paramBundle) {
     this.findPreference(Prefs.RINGTONE_PREF)
         .setOnPreferenceClickListener(preference -> {
           Uri current = Prefs.getNotificationRingtone(getContext());
+          if (current.toString().isEmpty()) current = null;  // silent
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java:52]: this was the reason why if you set default notification sound to silent, when opening again no option was marked since empty Uri is not Silent, Silent == null

**Review by Hocuri — APPROVED** [review]
