### PR TITLE
avoid race in processComposeControls during "reply privately"

### LINKED ISSUE #3508: sometimes "reply privately" doesn't quote the message
when you select a message in a group and click the "reply privately" option, sometimes it happens that the 1:1 chat is opened but the message you wanted to reply privately is not shown in the quote in the draft area.

I just tried with one message and it happened, but then going again to the chat and trying again, now it works, so it is not so easy to reproduce

### PR DESCRIPTION
**Pull request by adbenitez**
`processComposeControls()` spawns a background thread that uses the class field `chatId`, but by the time `setDraft(chatId, null)` is called to clear the draft, the `chatId` might be already the new selected chat for "reply privately"

close #3508

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/ConversationActivity.java [hunk 1]
```diff
@@ -1266,48 +1267,36 @@ else if (!body.isEmpty()){
...
-    if (refreshFragment) {
-      fragment.reload(recipient, chatId);
-      try {
-        int accId = rpc.getSelectedAccountId();
-        DcHelper.getNotificationCenter(this).updateVisibleChat(accId, chatId);
-      } catch (RpcException e) {
-        Log.e(TAG, "rpc.getSelectedAccountId() failed", e);
-      }
-    }
-
```
Comment (adbenitez) [inline src/main/java/org/thoughtcrime/securesms/ConversationActivity.java:1310]: it is not clear to me why this was needed at all, sendComplete() is only called on sending messages, I can't think on any case where pressing the send button could trigger a change of chat (maybe if you click a notification super-fast after clicking the send button?? in any case you don't want in that thread of the "send message" action then revert the chatId/selected chat to the chat where the message was sent

Comment (wchen342) [reply src/main/java/org/thoughtcrime/securesms/ConversationActivity.java:1310]: I guess it is used to refresh that chat after send? But if everything works without it then I guess it is unnecessary.
