### PR TITLE
do accounts migration in background

### LINKED ISSUE #4116: F-Droid version fails to start with ANR since 2.33.1
> visually, what happens looks like this:
>
> - i tap the delta icon
> - screen shows "black with delta logo" for maybe 15s
> - i get dropped back to the android "main screen/desktop"

The log captured with `adb logcat`:
```
12-12 11:16:13.317  2100  2156 D WindowManagerShell: onActivityRestartAttempt: topActivity=ComponentInfo{com.b44t.messenger/org.thoughtcrime.securesms.ConversationListActivity}, wasVisible=false
12-12 11:16:13.333  1290  1539 V WindowManager: Sent Transition (#3678) createdAt=12-12 11:16:13.273 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=18597 effectiveUid=10163 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.b44t.messenger/org.thoughtcrime.securesms.RoutingActivity } baseActivity=ComponentInfo{com.b44t.messenger/org.thoughtcrime.securesms.ConversationListActivity} topActivity=ComponentInfo{com.b44t.messenger/org.thoughtcrime.securesms.ConversationListActivity} origActivity=ComponentInfo{com.b44t.messenger/org.thoughtcrime.securesms.RoutingActivity} realActivity=ComponentInfo{com.b44t.messenger/org.thoughtcrime.securesms.ConversationListActivity} numActivities=1 lastActiveTime=544733346 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{36b7236 Task{4016a12 #18597 type=standard A=10163:com.b44t.messenger}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 0 - 0, 0) topActivityInfo=ActivityInfo{fce6aa4 org.thoughtcrime.securesms.RoutingActivity} launchCookies=[android.os.BinderProxy@4fc9582] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isTopActivityNoDisplay=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false isActivityStackTransparent=false lastNonFullscreenBounds=Rect(252, 545 - 828, 1625) capturedLink=null capturedLinkTimestamp=0 requestedVisibleTypes=-9 topActivityRequestOpenInBrowserEducationTimestamp=0 appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false eligibleForLetterboxEducation= false isLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false eligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 topActivityLetterboxAppWidth=-1 topActivityLetterboxAppHeight=-1 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false hasMinAspectRatioOverride=false topActivityLetterboxBounds=null cameraCompatTaskInfo=CameraCompatTaskInfo { freeformCameraCompatMode=inactive}} topActivityMainWindowFrame=null}, pipChange = null, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@9a57493, appThread = android.app.IApplicationThread$Stub$Proxy@1a99cd0, debugName = QuickstepLaunch }, displayChange = null, flags = 0, debugId = 3678 }
12-12 11:16:13.334  1290  1539 V WindowManager:         {WCT{RemoteToken{36b7236 Task{4016a12 #18597 type=standard A=10163:com.b44t.messenger}}} m=TO_FRONT f=MOVE_TO_TOP leash=Surface(name=Task=18597)/@0xc381e5b sb=Rect(0, 0 - 1080, 2160) eb=Rect(0, 0 - 1080, 2160) epz=Point(1080, 2160) d=0 taskParent=-1},
12-12 11:16:13.366  1290  1954 E JobScheduler.JobStatus: App com.b44t.messenger became active but still in NEVER bucket
12-12 11:16:14.185  1290  1539 V WindowManager:         {WCT{RemoteToken{36b7236 Task{4016a12 #18597 type=standard A=10163:com.b44t.messenger}}} m=TO_BACK f=NONE leash=Surface(name=Task=18597)/@0xc381e5b sb=Rect(0, 0 - 1080, 2160) eb=Rect(0, 0 - 1080, 2160) epz=Point(1080, 2160) d=0 taskParent=-1},
12-12 11:16:15.268  1290 27432 D CoreBackPreview: Window{7d641cc u0 Splash Screen com.b44t.messenger}: Setting back callback null
12-12 11:18:54.794  1290  1554 I ActivityManager: Extending process start timeout by 371ms for ProcessRecord{72b1b1e 13836:com.b44t.messenger/u0a163}
12-12 11:18:55.460  1290 13897 E ActivityManager: ANR in com.b44t.messenger
12-12 11:18:55.460  1290 13897 E ActivityManager: Reason: Process ProcessRecord{72b1b1e 13836:com.b44t.messenger/u0a163} failed to complete startup
12-12 11:18:55.463  1290 13897 I ActivityManager: Killing 13836:com.b44t.messenger/u0a163 (adj 0): bg anr
12-12 11:18:55.466  1290 13897 D ActivityManager: Completed ANR of com.b44t.messenger in 290ms, latency 1ms
12-12 11:18:55.560  1290  2241 W ActivityTaskManager: ProcessRecord{72b1b1e 13836:com.b44t.messenger/u0a163} is removed with pending start ActivityRecord{6751645 u0 com.b44t.messenger/org.thoughtcrime.securesms.RoutingActivity t18597}
```

### PR DESCRIPTION
**Pull request by adbenitez**
move accounts migration to background thread and wait for it in foreground  so `ApplicationContext.onCreate` can complete and we avoid ANR in background

Notes:
* in old android versions this was never a problem, there you get the "App is not responding, wait?" even if the app is stuck in ApplicationContext, this is only a problem in recent androids that will silently kill the app in that case
* In that initial state it seems newer Android considers the app in "background" and will report ANR much sooner than with this new approach, so there is even less chance the ANR is triggered at all
* Ideally one could have some "loading..." screen but I think this is good enough for 99% of the time, we should avoid heavy migrations in the future in any case
* I re-formated/indented the code in a separate commit to make it easier to review what lines where actually changed

close #4116

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/ApplicationContext.java [hunk 1]
```diff
@@ -88,17 +156,17 @@ public void onCreate() {
 
     System.loadLibrary("native-utils");
 
+    // Initialize DcAccounts in background to avoid ANR during SQL migrations
+    Util.runOnBackground(() -> {
+      synchronized (initLock) {
+        try {
+
     dcAccounts = new DcAccounts(new File(getFilesDir(), "accounts").getAbsolutePath());
```
Comment (link2xt) [inline src/main/java/org/thoughtcrime/securesms/ApplicationContext.java]: Did you test that if 5 minute sleep is inserted here (before this line) there is no background ANR?

Comment (adbenitez) [reply src/main/java/org/thoughtcrime/securesms/ApplicationContext.java]: yes, ofc, you also can test it inserting `Util.sleep(999999)` there

Comment (adbenitez) [reply src/main/java/org/thoughtcrime/securesms/ApplicationContext.java]: as I said in the issue description, it even takes longer to trigger the ANR, and when it happens you get the dialog with option to wait

**Comment by link2xt** [comment]
> I didn't re-format/indent the code to make it easier to review what lines where actually changed

Can also be reformatted, there is this option for review:
image

File: src/main/java/org/thoughtcrime/securesms/ApplicationContext.java [hunk 2]
```diff
@@ -73,6 +76,71 @@ public static ApplicationContext getInstance(@NonNull Context context) {
     return (ApplicationContext)context.getApplicationContext();
   }
 
+  /**
+   * Get DcAccounts instance, waiting for initialization if necessary.
+   * This method is thread-safe and will block until initialization is complete.
+   */
+  public static DcAccounts getDcAccounts() {
+    synchronized (initLock) {
```
Comment (link2xt) [inline src/main/java/org/thoughtcrime/securesms/ApplicationContext.java:80]: Common code from `getDcAccounts`, `getRpc` and `getDcContext` can be moved to a separate function that waits until initialized.
