### PR TITLE
move the file chooser implementation to WebxdcActivity class

### LINKED ISSUE #2585: crash opening HTML message in Android 4
an Android 4.2 user reported that opening an HTML message fails after the recent addition of https://github.com/deltachat/deltachat-android/pull/2575

### PR DESCRIPTION
**Pull request by adbenitez**
successor of https://github.com/deltachat/deltachat-android/pull/2575

close #2585

### CODE REVIEW

File: src/org/thoughtcrime/securesms/WebViewActivity.java [hunk 1]
```diff
@@ -127,22 +122,6 @@ public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceReque
         return super.shouldInterceptRequest(view, request);
       }
     });
-    webView.setWebChromeClient(new WebChromeClient() {
-      @Override
-      @RequiresApi(21)
-      public boolean onShowFileChooser(WebView webView, ValueCallback<Uri[]> filePathCallback, WebChromeClient.FileChooserParams fileChooserParams) {
-        if (WebViewActivity.this.filePathCallback != null) {
-          WebViewActivity.this.filePathCallback.onReceiveValue(null);
-        }
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/WebViewActivity.java:136]: I discarded this because it doesn't match the behavior of browsers, it is simulating a "nothing selected" event upon opening the chooser, which doesn't happen in real browsers, not even when the user cancels the file chooser (don't select anything)

File: src/org/thoughtcrime/securesms/WebViewActivity.java [hunk 2]
```diff
@@ -333,26 +312,6 @@ protected WebResourceResponse interceptRequest(String url) {
...
-            }
-          }
-        } catch (Exception e) {
-          e.printStackTrace();
-        }
-      }
-      filePathCallback.onReceiveValue(dataUris);
-      filePathCallback = null;
-    }
     super.onActivityResult(reqCode, resultCode, data);
```
Comment (r10s) [inline src/org/thoughtcrime/securesms/WebViewActivity.java:315]: i assume, the whole `@Override onActivityResult()` can be removed here as it does nothing else than calling `super.onActivityResult()`

File: src/org/thoughtcrime/securesms/WebViewActivity.java (hunk 1 above)
Comment (r10s) [reply src/org/thoughtcrime/securesms/WebViewActivity.java:136]: hm, i would leave it as is. iiuc, the even goes to previous selector, not to the current one. `WebViewActivity.this.filePathCallback.onReceiveValue(null)` is called only if there was previously a file request started that gets aborted. the 3 lines make sure, a request is always somehow ended.

the code comes from the AvancedWebView, so, unless we're really sure what we're doing better, i'd leave it and focus on shifting things in this pr. if you still think, it is wrong, please open a subsequent pr.

Comment (adbenitez) [reply src/org/thoughtcrime/securesms/WebViewActivity.java:136]: but why would you send such event to the previous callback when calling a new one? the old one already received the call, also the callback is set to null every time the response is received so I think this doesn't even happens never :thinking:

File: src/org/thoughtcrime/securesms/WebViewActivity.java (hunk 2 above)
Comment (adbenitez) [reply src/org/thoughtcrime/securesms/WebViewActivity.java:315]: yes, I was thinking that as well, but since it was like that even before adding this code, I thought it was intentional, will remove it then

File: src/org/thoughtcrime/securesms/WebViewActivity.java (hunk 1 above)
Comment (r10s) [reply src/org/thoughtcrime/securesms/WebViewActivity.java:136]: > but why would you send such event to the previous callback when calling a new one?

https://developer.android.com/reference/android/webkit/WebChromeClient#onShowFileChooser says that for canceling a request, we should pass `null` - so, if forever reason, onShowFileChooser() is triggered again before we close the dialog, we should cancel the previous callback

i agree that it should not happen normally

Comment (adbenitez) [reply src/org/thoughtcrime/securesms/WebViewActivity.java:136]: ok, I reverted it, it should not hurt to have in the end

**Review by r10s — APPROVED** [review]
lgtm now, thanks for fixing!
