### PR TITLE
avoid NullPointerException when selecting thumbnail image

### LINKED ISSUE #2156: App crashes when attaching image after search in-chat
This bug was reported by the Italian DC community, thanks!

- Delta Chat version: 1.24
- Steps to reproduce the problem:
   1. open a chat
   2. search for something in chat
   3. end the search
   4. click the attachment button, select an image from the images thumbnails
   5. app crashes with `NullPointerException`
- Logs:
```
11-29 19:09:43.831 16273 16273 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.thoughtcrime.securesms.components.ThumbnailView.clear(org.thoughtcrime.securesms.mms.GlideRequests)' on a null object reference
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.mms.AttachmentManager$2.onPreExecute(AttachmentManager.java:234)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:724)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.mms.AttachmentManager.setMedia(AttachmentManager.java:372)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationActivity.setMedia(ConversationActivity.java:1018)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationActivity.onActivityResult(ConversationActivity.java:398)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationActivity$AttachmentTypeListener.onQuickAttachment(ConversationActivity.java:1408)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.components.AttachmentTypeSelector$RecentPhotoSelectedListener.onItemClicked(AttachmentTypeSelector.java:287)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.components.RecentPhotoViewRail$RecentPhotoAdapter.lambda$onBindItemViewHolder$0$org-thoughtcrime-securesms-components-RecentPhotoViewRail$RecentPhotoAdapter(RecentPhotoViewRail.java:124)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at org.thoughtcrime.securesms.components.RecentPhotoViewRail$RecentPhotoAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.view.View.performClick(View.java:8160)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:8137)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.view.View.access$3700(View.java:888)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:30236)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:246)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8587)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
11-29 19:09:43.831 16273 16273 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130
```

### PR DESCRIPTION
**Pull request by adbenitez**
close #2156

### CODE REVIEW

File: src/org/thoughtcrime/securesms/ConversationActivity.java [hunk 1]
```diff
@@ -1582,16 +1581,12 @@ private void searchExpand(final Menu menu, final MenuItem searchItem) {
     beforeSearchComposeVisibility = composePanel.getVisibility();
     composePanel.setVisibility(View.GONE);
 
-    beforeSearchAttachVisibility = attachmentManager.getVisibility();
-    attachmentManager.setVisibility(View.GONE);
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/ConversationActivity.java:1586]: apparently calling this causes `AttachmentManager.attachmentViewStub.resolved()` to be `true` then if you never attached an image before `inflateStub()` was not called and all the views are `null` and will not be initialized since `inflateStub()` only initialize them if `attachmentViewStub.resolved() == false`

Comment (r10s) [reply src/org/thoughtcrime/securesms/ConversationActivity.java:1586]: thanks for explanation, indeed, i was wondering, at a first glance :)

**Review by Hocuri — APPROVED** [review]
I don't know enough about ViewStubs to directly say whether this makes sense.

But this PR can be merged anyway I think, it won't make things worse, for the reason @adbenitez pointed out the removed code wasn't needed anyway.

So, in the worst case it removes unused code, in the best case it fixes an issue. Thanks @adbenitez!

**Comment by adbenitez** [comment]
> in the best case it fixes an issue. Thanks @adbenitez!

yes, it fixed the issue, at least in my phone :D
