### PR TITLE
Promote call FGS asap

### LINKED ISSUE #4375: VoIP Crash on Android 16: SecurityException when starting microphone FGS (SDK 36)
**Description:**
Delta Chat 2.49.0 consistently crashes on Android 16 (SDK 36) when answering an incoming call while the app is in the background. 

The crash occurs immediately after pressing "Answer" on the system notification. It appears that under SDK 36, the system requirements for transitioning a background app to a "microphone" foreground service have become stricter. The implementation is failing the "eligible state" check, likely because the service is being started from a background thread pool rather than the immediate context of the user interaction.

**Environment:**
* **App Version:** 2.49.0-gplay (versionCode 747)
* **Device:** Samsung SM-S9060
* **OS:** Android 16 (SDK 36)
* **Battery Optimizations:** Disabled/Ignored

**Steps to Reproduce:**
1. Ensure Delta Chat is running in the background.
2. Receive an incoming VoIP call.
3. Press "Answer" from the system notification or lock screen.
4. The app crashes immediately.  Even if I open the app itself first and only then click "Answer", it still crashes. 
There are 2 ways of  reliably answering the phone call:
- first  open the app, click on the person who is ringing and click the phone icon in the chat itself.
- don't click on "Answer", but rather click on the ringing pop-up  itself, the decline\answer window opens up,  then let the app ring for 6-10 seconds and then click "answer"

**Technical info:**
The crash is a `java.lang.SecurityException: Starting FGS with type microphone`. 
In Android 16, starting a Foreground Service (FGS) with the `microphone` type is restricted unless the app is in an "eligible state." The logs show the crash occurring on `pool-6-thread-1`. .

**Logcat Excerpt:**
```text
AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
AndroidRuntime: Process: chat.delta, PID: 19275
AndroidRuntime: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{...} targetSDK=36 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3354)
AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3338)
AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3321)
AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3263)
AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7539)
AndroidRuntime: 	at android.app.Service.startForeground(Service.java:776)
AndroidRuntime: 	at f7.r.w(SourceFile:242)
AndroidRuntime: 	at f7.r.r(SourceFile:71)
AndroidRuntime: 	at A7.g.run(SourceFile:356)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1564)
```

### PR DESCRIPTION
**Pull request by wchen342**
The likely cause is somehow the RPC call is slow and the foreground promotion did not happen soon enough.

Fixes #4375

#skip-changelog

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/calls/CallCoordinator.java [hunk 1]
```diff
@@ -402,6 +402,15 @@ public synchronized void handleCallControlScopeAnswer() {
...
     }
 
+    // Promote the service to foreground immediately. Waiting until onIncomingCallAccepted
+    // on executor pool thread is too late on stricter OEM.
+    //
+    // Do not cancel() but use showOrUpdateOngoingNotification to replace incoming
+    // notification without a gap.
+    String callerName = displayName.getValue();
+    if (callerName == null) callerName = "Unknown";
+    showOrUpdateOngoingNotification("Call with " + callerName);
```
Comment (adbenitez) [inline src/main/java/org/thoughtcrime/securesms/calls/CallCoordinator.java]: hardcoded unstranslated string?

Comment (wchen342) [reply src/main/java/org/thoughtcrime/securesms/calls/CallCoordinator.java]: It's actually like this for all calls for this function. Let me change them together.

Comment (wchen342) [reply src/main/java/org/thoughtcrime/securesms/calls/CallCoordinator.java]: Updated.

File: src/main/AndroidManifest.xml [hunk 2]
```diff
@@ -71,6 +71,7 @@
         android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK" />
     <uses-permission android:name="android.permission.FOREGROUND_SERVICE_CAMERA" />
     <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MICROPHONE" />
+    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_PHONE_CALL" />
```
Comment (adbenitez) [inline src/main/AndroidManifest.xml:74]: this makes sense, I am wondering how it was working (to use the "incoming call" notification style API stuff without it, I would have expected foregroundServiceType == phoneCall would have been a requirement for such notification

Comment (wchen342) [reply src/main/AndroidManifest.xml:74]: Technically it shall work without this permission because we promote the service to foreground when the app activity is in foreground already, but obviously there seems to be some timing issues. This is supposed to loosen the restrictions so it is added for extra safety.

**Comment by adbenitez** [comment]
I have not checked if it is introduced by this PR or existing problem, but now while testing this branch:

I started an audio call, got asked for mic permission, I grant it, then the call ended instead of proceeding, in the log I see "No active call exists, cannot proceed":

```
2026-04-24 18:55:17.077  6569-6569  CallUtil                com.b44t.messenger.beta              D  Starting audio call to 12
2026-04-24 18:55:17.077  6569-6569  CallCoordinator         com.b44t.messenger.beta              D  Initiating outgoing call:accId=1, chatId=12
2026-04-24 18:55:17.078  6569-6569  CallCoordinator         com.b44t.messenger.beta              E  Microphone permission not granted
2026-04-24 18:55:17.088  6569-6569  WindowOnBackDispatcher  com.b44t.messenger.beta              D  setTopOnBackInvokedCallback (unwrapped): null
2026-04-24 18:55:17.186  6569-7008  org.webrtc.Logging      com.b44t.messenger.beta              I  EglBase14Impl: Using OpenGL ES version 2
2026-04-24 18:55:17.192  6569-6569  org.webrtc.Logging      com.b44t.messenger.beta              I  EglRenderer: local_video_viewInitializing EglRenderer
2026-04-24 18:55:17.193  6569-7009  org.webrtc.Logging      com.b44t.messenger.beta              I  EglBase14Impl: Using OpenGL ES version 2
2026-04-24 18:55:17.198  6569-6569  org.webrtc.Logging      com.b44t.messenger.beta              I  EglRenderer: remote_video_viewInitializing EglRenderer
2026-04-24 18:55:17.198  6569-6569  CallActivity            com.b44t.messenger.beta              D  Video renderers initialized
2026-04-24 18:55:17.199  6569-6569  CallActivity            com.b44t.messenger.beta              D  Proximity wake lock initialized
2026-04-24 18:55:17.200  6569-6569  CallViewModel           com.b44t.messenger.beta              D  CallViewModel created
2026-04-24 18:55:17.200  6569-6569  CallViewModel           com.b44t.messenger.beta              D  Initializing CallViewModel
2026-04-24 18:55:17.200  6569-6569  CallViewModel           com.b44t.messenger.beta              D  CallViewModel initialized
2026-04-24 18:55:17.200  6569-6569  CallActivity            com.b44t.messenger.beta              D  CallViewModel initialized
2026-04-24 18:55:17.213  6569-6569  CallActivity            com.b44t.messenger.beta              D  Call state: RINGING
2026-04-24 18:55:17.213  6569-6569  CallActivity            com.b44t.messenger.beta              D  TURN relay is NOT being used
2026-04-24 18:55:17.223  6569-6569  WindowOnBackDispatcher  com.b44t.messenger.beta              D  setTopOnBackInvokedCallback (unwrapped): android.app.Activity$$ExternalSyntheticLambda0@cc2af31
2026-04-24 18:55:17.223  6569-6569  WindowOnBackDispatcher  com.b44t.messenger.beta              D  setTopOnBackInvokedCallback (unwrapped): androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@12bb616
2026-04-24 18:55:17.228  6569-6569  VRI[CallActivity]       com.b44t.messenger.beta              D  WindowInsets changed: 1080x2400 statusBars:[0,132,0,0] navigationBars:[0,0,0,63] mandatorySystemGestures:[0,164,0,84] 
2026-04-24 18:55:17.410  6569-6569  VRI[Conver...nActivity] com.b44t.messenger.beta              D  visibilityChanged oldVisibility=true newVisibility=false
2026-04-24 18:55:17.410  6569-6569  VRI[PopupWindow:c7e438] com.b44t.messenger.beta              D  visibilityChanged oldVisibility=true newVisibility=false
2026-04-24 18:55:17.422  6569-6658  HWUI                    com.b44t.messenger.beta              D  endAllActiveAnimators on 0xb400d9dc4ce8ae00 (MenuPopupWindow$MenuDropDownListView) with handle 0xb400d8b00dfeeb40
2026-04-24 18:55:17.430  6569-6569  WindowOnBackDispatcher  com.b44t.messenger.beta              D  setTopOnBackInvokedCallback (unwrapped): android.app.Activity$$ExternalSyntheticLambda0@fbd9676
2026-04-24 18:55:17.532  6569-6569  ViewRootImpl            com.b44t.messenger.beta              D  Skipping stats log for color mode
2026-04-24 18:55:18.608  6569-6569  CallActivity            com.b44t.messenger.beta              D  handleIntents: action=null
2026-04-24 18:55:18.608  6569-6569  CallActivity            com.b44t.messenger.beta              E  No active call exists, cannot proceed
2026-04-24 18:55:18.621  6569-6569  WindowOnBackDispatcher  com.b44t.messenger.beta              D  setTopOnBackInvokedCallback (unwrapped): androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@cd53477
2026-04-24 18:55:19.234  6569-6569  VRI[CallActivity]       com.b44t.messenger.beta              D  visibilityChanged oldVisibility=true newVisibility=false
2026-04-24 18:55:19.252  6569-6569  WindowOnBackDispatcher  com.b44t.messenger.beta              D  setTopOnBackInvokedCallback (unwrapped): android.app.Activity$$ExternalSyntheticLambda0@cc2af31
2026-04-24 18:55:19.254  6569-6569  CallViewModel           com.b44t.messenger.beta              D  CallViewModel cleared
2026-04-24 18:55:19.254  6569-6569  WindowOnBackDispatcher  com.b44t.messenger.beta              D  setTopOnBackInvokedCallback (unwrapped): null
```

then I try to call again this time it worked because the mic permission dialog was not appearing as it was already granted

**Comment by wchen342** [comment]
It's a pre-existing problem. I'll fix it in a separate pr.

**Review by adbenitez — APPROVED** [review]
seems to work as expected, thanks for fixing!
