### PR TITLE
fix IntentUtils.showBrowserIntent() and use it everywhere

### LINKED ISSUE #3534: ActivityNotFoundException in IntentUtils.showBrowserIntent
```
Exception android.content.ActivityNotFoundException:
  at android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:2274)
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1893)
  at android.app.Activity.startActivityForResult (Activity.java:5796)
  at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:780)
  at android.app.Activity.startActivityForResult (Activity.java:5749)
  at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:761)
  at android.app.Activity.startActivity (Activity.java:6267)
  at android.app.Activity.startActivity (Activity.java:6234)
  at org.thoughtcrime.securesms.util.IntentUtils.showBrowserIntent (IntentUtils.java:24)
  at org.thoughtcrime.securesms.qr.QrCodeHandler.lambda$showQrUrl$10$org-thoughtcrime-securesms-qr-QrCodeHandler (QrCodeHandler.java:185)
  at org.thoughtcrime.securesms.qr.QrCodeHandler$$ExternalSyntheticLambda9.onClick (Unknown Source:4)
  at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage (AlertController.java:167)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:222)
  at android.os.Looper.loop (Looper.java:314)
  at android.app.ActivityThread.main (ActivityThread.java:8602)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:565)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1081)
```

### PR DESCRIPTION
**Pull request by adbenitez**
fix IntentUtils.showBrowserIntent(), rename to `showInBrowser` and use it everywhere instead of having duplicate code 

close #3534

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/util/IntentUtils.java [hunk 1]
```diff
@@ -21,7 +25,11 @@ public static boolean isResolvable(@NonNull Context context, @NonNull Intent int
 
   public static void showBrowserIntent(Context context, String url) {
```
Comment (Hocuri) [inline src/main/java/org/thoughtcrime/securesms/util/IntentUtils.java:26]: What about renaming it to `showInBrowser()`? `showBrowserIntent()` sounds to me like it will return an intent that shows the URL in the browser.

**Review by Hocuri — APPROVED** [review]
Nice, thanks for fixing!

File: src/main/java/org/thoughtcrime/securesms/util/IntentUtils.java (hunk 1 above)
Comment (adbenitez) [reply src/main/java/org/thoughtcrime/securesms/util/IntentUtils.java:26]: Good idea!
