### PR TITLE
fix: Fetch synchronously in the background if no foreground service is allowed

### LINKED ISSUE #3500: Crash when receiving a message from FCM but battery usage is restricted
Steps to reproduce:
- Use a chatmail account and a DC build with Google Play services enabled
- In the system settings, enable "Apps -> Delta Chat -> App Battery usage -> Restricted"
- Swipe away DC so that it's not running in the background
- Receive a message

The crash, as reported via the Google Play Console:
```
Exception android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service chat.delta/org.thoughtcrime.securesms.service.FetchForegroundService
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:54)
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:50)
  at android.os.Parcel.readParcelableInternal (Parcel.java:4775)
  at android.os.Parcel.readParcelable (Parcel.java:4743)
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3006)
  at android.os.Parcel.createException (Parcel.java:2995)
  at android.os.Parcel.readException (Parcel.java:2978)
  at android.os.Parcel.readException (Parcel.java:2920)
  at android.app.IActivityManager$Stub$Proxy.startService (IActivityManager.java:5335)
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1894)
  at android.app.ContextImpl.startForegroundService (ContextImpl.java:1870)
  at android.content.ContextWrapper.startForegroundService (ContextWrapper.java:822)
  at androidx.core.content.ContextCompat$Api26Impl.startForegroundService (ContextCompat.java:1128)
  at androidx.core.content.ContextCompat.startForegroundService (ContextCompat.java:700)
  at org.thoughtcrime.securesms.service.FetchForegroundService.start (FetchForegroundService.java:36)
  at org.thoughtcrime.securesms.notifications.FcmReceiveService.onMessageReceived (FcmReceiveService.java:94)
  at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage (FirebaseMessagingService.java:243)
  at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk (FirebaseMessagingService.java:193)
  at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent (FirebaseMessagingService.java:179)
  at com.google.firebase.messaging.FirebaseMessagingService.handleIntent (FirebaseMessagingService.java:168)
  at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$com-google-firebase-messaging-EnhancedIntentService (EnhancedIntentService.java:82)
  at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda0.run (Unknown Source:6)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at com.google.android.gms.common.util.concurrent.zza.run (com.google.android.gms:play-services-basement@@18.3.0:2)
  at java.lang.Thread.run (Thread.java:1012)
```

The problem is that we're not allowed to start a foreground service if battery usage is "restricted".

### PR DESCRIPTION
**Pull request by Hocuri**
Fix #3500.

### CODE REVIEW

File: src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java [hunk 1]
```diff
@@ -30,15 +32,40 @@ public static void start(Context context) {
...
+        // The background fetch was successful, but we need to wait until all events were processed.
+        // After all events were processed, we will get DC_EVENT_ACCOUNTS_BACKGROUND_FETCH_DONE,
+        // and stop() will be called.
+        while (fetchingSynchronously) {
+          try {
+            // The `wait()` needs to be enclosed in a while loop because there may be
+            // "spurious wake-ups", i.e. `wait()` may return even though `notifyAll()` wasn't called.
+            STOP_NOTIFIER.wait();
+          } catch (InterruptedException ex) { }
+        }
```
Comment (Hocuri) [inline src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java:58]: In order to simplify the logic here, we could also simply call Thread.sleep(1000) and assume that the UI will be done with showing a notification within 1s.

Comment (adbenitez) [reply src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java:58]: I don't think the logic is too complicated, and it is well documented, better than some fixed sleeping that might be too much in some cases and too little in another

**Review by adbenitez — APPROVED** [review]
