### PR TITLE
use only one `audioFocusChangeListener`

### LINKED ISSUE #2700: cannot play same the voice message twice in succession
to reproduce, play a voice message, hit pause and try to hit "play" again - this does not work

funnily, "play" does work again, if you play another voice message in between

this bug was probably introduced by #2686 and was not released

### PR DESCRIPTION
**Pull request by r10s**
use only one `audioFocusChangeListener`
as otherwise the "old" will immediately pause
when we restart playing.

moreover, this pr switches to the new `requestAudioFocus()` api

closes #2700

### CODE REVIEW

File: src/org/thoughtcrime/securesms/components/AudioView.java [hunk 1]
```diff
@@ -39,6 +41,7 @@ public class AudioView extends FrameLayout implements AudioSlidePlayer.Listener
   private final @NonNull TextView        title;
 
   private @Nullable AudioSlidePlayer   audioSlidePlayer;
+  AudioManager.OnAudioFocusChangeListener audioFocusChangeListener;
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/components/AudioView.java:44]:
```suggestion
  private AudioManager.OnAudioFocusChangeListener audioFocusChangeListener;
```

Comment (r10s) [reply src/org/thoughtcrime/securesms/components/AudioView.java]: thanks!

**Review by adbenitez — APPROVED** [review]
:ok_hand:
