### PR TITLE
use synchronized block to avoid IllegalMonitorStateException

### LINKED ISSUE #3525: Exception due to new push notification handling
it seems in some devices the new push notifications handling introduced at #3501 is causing fatal exception:

```
01-09 15:11:11.178 13254 13287 🔴 AndroidRuntime: FATAL EXCEPTION: eventThread
01-09 15:11:11.178 13254 13287 🔴 AndroidRuntime: Process: com.github.arcanechat, PID: 13254
01-09 15:11:11.178 13254 13287 🔴 AndroidRuntime: java.lang.IllegalMonitorStateException: object not locked by thread before notify()
01-09 15:11:11.178 13254 13287 🔴 AndroidRuntime: 	at java.lang.Object.notifyAll(Native Method)
01-09 15:11:11.178 13254 13287 🔴 AndroidRuntime: 	at org.thoughtcrime.securesms.service.FetchForegroundService.b(SourceFile:1)
01-09 15:11:11.178 13254 13287 🔴 AndroidRuntime: 	at ab.j0.run(SourceFile:1128)
01-09 15:11:11.178 13254 13287 🔴 AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: Process: com.github.arcanechat, PID: 13254
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: java.lang.IllegalMonitorStateException: object not locked by thread before wait()
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: 	at java.lang.Object.wait(Native Method)
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: 	at java.lang.Object.wait(Object.java:386)
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: 	at java.lang.Object.wait(Object.java:524)
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: 	at org.thoughtcrime.securesms.service.FetchForegroundService.a(SourceFile:86)
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.FcmReceiveService.d(SourceFile:1)
01-09 15:11:11.179 13254 19386 🔴 AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.b(SourceFile:317)

```

this two exceptions are caused by `STOP_NOTIFIER.notifyAll();` and `STOP_NOTIFIER.wait();` in `org.thoughtcrime.securesms.service.FetchForegroundService`

### PR DESCRIPTION
**Pull request by adbenitez**
close #3525

### CODE REVIEW

**Comment by adbenitez** [comment]
oh mannnn, all the CI actions decided to go nuts right on my PR

**Comment by r10s** [comment]
what exactly does `synchronized` do? if it is sort of mutula-exclusive-critical-section, and wait would get access to that, notifyAll could never be called. but not sure, i am currently deep in iOS release thingies ...

**Comment by adbenitez** [comment]
> what exactly does `synchronized` do? if it is sort of mutula-exclusive-critical-section, and wait would get access to that, notifyAll could never be called. but not sure, i am currently deep in iOS release thingies ...

I was wondering exactly the same, that is why I was a bit skeptical when read that it is the solution to the problem in https://stackoverflow.com/a/24186147

but then I searched our code and in **all** other places where we use `wait()` and `notifyAll()` we always do it exactly as recommended inside a `synchronized` block, so then I assume it is fine without further investigation, plus the crash by android is telling that you must lock the object before making the call in both cases

File: src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java [hunk 1]
```diff
@@ -53,7 +53,9 @@ public static void start(Context context) {
           try {
             // The `wait()` needs to be enclosed in a while loop because there may be
             // "spurious wake-ups", i.e. `wait()` may return even though `notifyAll()` wasn't called.
-            STOP_NOTIFIER.wait();
+            synchronized (STOP_NOTIFIER) {
+              STOP_NOTIFIER.wait();
+            }
           } catch (InterruptedException ex) { }
         }
       }
```
[the remark this answers is not in the document]
Comment (Hocuri) [reply src/main/java/org/thoughtcrime/securesms/service/FetchForegroundService.java]: Since I can't create a suggestion here on GitHub (since it would touch unchanged lines), I just pushed a commit with my suggestion

File: .github/workflows/preview-apk.yml [hunk 2]
```diff
@@ -49,7 +49,7 @@ jobs:
         run: ./gradlew --no-daemon assembleGplayDebug
 
       - name: Upload APK
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
```
Comment (Hocuri) [inline .github/workflows/preview-apk.yml:52]: Commited accidentally?

**Review by Hocuri — APPROVED** [review]
It's amazing how hard these Java APIs are to be used correctly XD

File: .github/workflows/preview-apk.yml (hunk 2 above)
Comment (adbenitez) [reply .github/workflows/preview-apk.yml:52]: CI fails otherwise
