### PR TITLE
fix permissions for ~ android 11

### LINKED ISSUE #2726: Cannot grant permission to access storage (impossible to restore from backup)
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.211001.001 a4d837813c from 2023-09-20).

- Delta Chat version:
1.41 (latest nightly build).

- Expected behavior:
To be able to grant permission to Delta Chat to access storage.

- Actual behavior:
Permission cannot be granted to Delta Chat to access storage.

- Steps to reproduce the problem:
-- Launch the app and select `Restore from Backup`.
-- When asked to grant permission to access storage, tap `CONTINUE`. (You will be guided to the app permission settings for Delta Chat in Android, but unfortunately "Storage" is not available and, therefore, cannot be selected.)

- Screenshots:

-- Expected:
grafik

-- Actual:
grafik
grafik

- Logs:
N/A.

### PR DESCRIPTION
**Pull request by r10s**
fixes #2726 

- [x] fix import backup from welcome activity on android 11
- [x] check _other file access_ points on android 11
- [x] check other androids (i assume, android10 is same as android11, so the change should be at sdk29 already, but that needs to be double checked and tested)  
    - EDIT: tried at least import-after-fresh-install, export-image, camera-roll on:
        - android5 (sdk21): ok
        - android9 (sdk28): ok
        - android10 (sdk29): ok
        - android11 (sdk30): ok
        - _android12 (sdk31): cannot test, emulator issues_
        - android12 (sdk32): ok
        - android13 (sdk33): ok
    - EDIT: tried backup-after-fresh-install-without-any-rights-granted:
        - android5 (sdk21): ok
        - android9 (sdk28): ok
        - android10 (sdk29): ok
        - android11 (sdk30): ok
        - android12 (sdk32): ok
        - android13 (sdk33): ok

_other file access points_ are:
- export media from chat
- export media from gallery
- export keys
- export log
- export backup
- import key
- import backup on welcome screen

### CODE REVIEW

**Comment by adbenitez** [comment]
about Android 10: 
https://stackoverflow.com/questions/64221188/write-external-storage-when-targeting-android-10
https://developer.android.com/about/versions/10/privacy/changes#scoped-storage

**Comment by r10s** [comment]
seems as if sdk29 is fine already. so, this pr really fixes only android11 on-point, from the logic, the older androids should be unchanged

**Comment by r10s** [comment]
@adbenitez for logic review, i think, that paths of other android-versions are not changed, seems calming

**Comment by r10s** [comment]
back to draft: android12 seems special ...

**Comment by adbenitez** [comment]
> back to draft: android12 seems special ... ooh no, was on a wrong branch :) have to check the things again ...

oh :( talk about android fragmentation

**Comment by r10s** [comment]
so, finally, this is ready for review; i double checked the android versions mentioned above ...

File: src/org/thoughtcrime/securesms/permissions/Permissions.java [hunk 1]
```diff
@@ -100,6 +102,20 @@ public PermissionsBuilder ifNecessary(boolean condition) {
       return this;
     }
 
+    public PermissionsBuilder alwaysGrantOnSdk30() {
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/permissions/Permissions.java:105]: I would just have a generic function `alwaysGrantOnSdk(int version)` and then call `Permissions.alwaysGrantOnSdk(30)` etc.

File: src/org/thoughtcrime/securesms/ShareActivity.java [hunk 2]
```diff
@@ -138,6 +138,7 @@ private boolean needsFilePermission(List<Uri> uris) {
   private void requestPermissionForFiles(List<Uri> streamExtras) {
     Permissions.with(this)
             .request(Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE)
```
Comment (adbenitez) [inline src/org/thoughtcrime/securesms/ShareActivity.java:140]: `WRITE_EXTERNAL_STORAGE` is ".alwaysGrantOnSdk30()" in other places, does this mean that it will be requested for SDK 30 here? what are the implications?

**Review by adbenitez — APPROVED** [review]
great! thanks for fixing and enduring having to try in all that emulators! overall the code looks good, I can't test it myself other than in sdk 33

File: src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java [hunk 3]
```diff
@@ -266,7 +266,8 @@ public boolean onPreferenceClick(Preference preference) {
 
   private void performBackup() {
     Permissions.with(getActivity())
-            .request(Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE)
+            .request(Manifest.permission.WRITE_EXTERNAL_STORAGE)
```
[the remark this answers is not in the document]
Comment (r10s) [reply src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java:269]: > doesn't core needs READ_EXTERNAL_STORAGE to read the folder content and generate the backup names

good point, then we'll better leave this unchanged - but i'll add a little comment

**Comment by r10s** [comment]
quite some stuff :)

Screenshot 2023-10-12 at 15 49 41

File: src/org/thoughtcrime/securesms/ShareActivity.java (hunk 2 above)
Comment (r10s) [reply src/org/thoughtcrime/securesms/ShareActivity.java:140]: i assume, that should be `alwaysGrantOnSdk30()` as well :)

Comment (r10s) [reply src/org/thoughtcrime/securesms/ShareActivity.java:140]: hm, not sure. in contrast to the other places, this uses some `file:` protocol, that may indeed require these rights (similar to the camera-roll, that also requires READ_EXTERNAL_STORAGE between sdk30..sdk32 (implicitly requested by galleryPermissions()). let's leave this as it was before (so, only change this for sdk33 where the permissions are gone.

might be, that we would better use galleryPermissions() for sdk33 here - but i anyway assume that "files" are playing less and less roles on newer androids, so, probably everything's fine. if not - we can iterate, if things are wrong on testing

File: src/org/thoughtcrime/securesms/permissions/Permissions.java (hunk 1 above)
Comment (r10s) [reply src/org/thoughtcrime/securesms/permissions/Permissions.java:105]: yeah, let's leave this as is for now. it looks more explicit that 33/30 is no typo in a parameter :)
