### PR TITLE
Relay to multiple contacts, rework message relaying

### LINKED ISSUE #1340: Share to multiple contacts
- Expected behavior: When sharing to Delta Chat and then long-clicking an app, DC crashes.
- Actual behavior: It should be possible to share to multiple contacts.
- Logs:
```
   java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Menu androidx.appcompat.view.ActionMode.getMenu()' on a null object reference
        at org.thoughtcrime.securesms.ConversationListFragment.onItemLongClick(ConversationListFragment.java:452)
        at org.thoughtcrime.securesms.ConversationListAdapter.lambda$onCreateViewHolder$2$ConversationListAdapter(ConversationListAdapter.java:122)
        at org.thoughtcrime.securesms.-$$Lambda$ConversationListAdapter$3T41Mf7zUsZE6210NC1tTC1ZMVI.onLongClick(Unknown Source:4)
        at android.view.View.performLongClickInternal(View.java:6677)
        at android.view.View.performLongClick(View.java:6635)
        at android.view.View.performLongClick(View.java:6653)
        at android.view.View$CheckForLongPress.run(View.java:25854)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### PR DESCRIPTION
**Pull request by Hocuri**
Fix #1340.

Also, I did extensive testing of message relaying:
- I. share and II. forward
- a. text
  b. text and one image
  c. 2 images
  d. 1 file (unknown type)
  e. 2 files (unknown type)
- to:
  1. 1 chat (just tap on it)
  2. If applicable: go back and forth a bit to test drafts
  3. 2 chats (multi-relaying)

and some of the bugs I found and fixed were probably already there before, although I did not test this.

After fixing things, I went through this list again and everything worked.

Seems like at some places in the UI the chatId is saved as a long, which seems not to make much sense because the core saves them as int. Anyway, I had to cast them.

### CODE REVIEW

File: src/org/thoughtcrime/securesms/ConversationListFragment.java [hunk 1]
```diff
@@ -446,12 +476,14 @@ public void onItemClick(ConversationListItem item) {
   public void onItemLongClick(ConversationListItem item) {
     actionMode = ((AppCompatActivity)getActivity()).startSupportActionMode(ConversationListFragment.this);
 
-    getListAdapter().initializeBatchMode(true);
-    getListAdapter().toggleThreadInBatchSet(item.getChatId());
-    getListAdapter().notifyDataSetChanged();
-    Menu menu = actionMode.getMenu();
-    if (menu != null) {
+    if (actionMode != null) {
```
Comment (Hocuri) [inline src/org/thoughtcrime/securesms/ConversationListFragment.java:479]: The crash I mentioned in the issue was because actionMode was null.

File: src/org/thoughtcrime/securesms/util/SendMessageUtil.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+import java.util.Set;
+
+import static android.app.Activity.RESULT_OK;
+import static org.thoughtcrime.securesms.util.RelayUtil.getForwardedMessageIDs;
+import static org.thoughtcrime.securesms.util.RelayUtil.getSharedText;
+import static org.thoughtcrime.securesms.util.RelayUtil.getSharedUris;
+import static org.thoughtcrime.securesms.util.RelayUtil.isForwarding;
+import static org.thoughtcrime.securesms.util.RelayUtil.isSharing;
+
+public class SendMessageUtil {
```
Comment (Hocuri) [inline src/org/thoughtcrime/securesms/util/SendMessageUtil.java:32]: I do not like the name of this class and think I will either merge it with RelayUtil or rename it to RelayMessageUtil. What do you think is better?

File: src/org/thoughtcrime/securesms/util/SendMessageUtil.java [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+  private static final String TAG = SendMessageUtil.class.getSimpleName();
+
+  public static void immediatelyRelay(Activity activity, Set<Long> chatIds) {
+    Util.runOnAnyBackgroundThread(() -> {
+      for (long chatId : chatIds) {
+        immediatelyRelayInner(activity, (int) chatId);
```
Comment (Hocuri) [inline src/org/thoughtcrime/securesms/util/SendMessageUtil.java:35]: Why does getListAdapter().getBatchSelections() return a Set<Long>? It has to be converted to `int` here, which is not a problem but definitely bad style.

**Comment by cyBerta** [comment]
@Hocuri this PR is marked as a draft. Did you make a plan with @r10s if/when/how to proceed with this one? I'm just asking because I'm still assigned as a reviewer (and I am also happy to unassign myself if there's someone who is deeper in the DC Android dev right now with capacities to test and review)

**Comment by Hocuri** [comment]
This was a should not have been marked as a draft, I was done with this PR.
